version: '2'
services:

  mysql:
    container_name: mysql
    image: mysql:5
    ports:
      - 3306:3306
    volumes:
      - ./volumes/mysql:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - ${PHPMYADMIN_PORT_MAPPING}
    links:
      - mysql:db

networks:
  default:
    external:
      name: ${APP_NETWORK}
